package com.aegisfit.healthconnect

import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.LinearLayout
import android.widget.TextView
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.result.contract.ActivityResultContracts
import androidx.health.connect.client.HealthConnectClient
import androidx.health.connect.client.PermissionController
import androidx.health.connect.client.aggregate.AggregateRequest
import androidx.health.connect.client.permission.HealthPermission
import androidx.health.connect.client.records.HeartRateRecord
import androidx.health.connect.client.records.StepsRecord
import androidx.health.connect.client.records.TotalCaloriesBurnedRecord
import androidx.health.connect.client.time.TimeRangeFilter
import androidx.health.connect.client.records.ReadRecordsRequest
import androidx.lifecycle.lifecycleScope
import kotlinx.coroutines.launch
import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL
import java.time.Instant
import java.time.temporal.ChronoUnit
import kotlin.math.roundToInt

class MainActivity : ComponentActivity() {
    private lateinit var serverUrl: EditText
    private lateinit var pairCode: EditText
    private lateinit var status: TextView
    private lateinit var client: HealthConnectClient

    private val permissions = setOf(
        HealthPermission.getReadPermission(StepsRecord::class),
        HealthPermission.getReadPermission(HeartRateRecord::class),
        HealthPermission.getReadPermission(TotalCaloriesBurnedRecord::class)
    )

    private val permissionLauncher = registerForActivityResult(
        PermissionController.createRequestPermissionResultContract()
    ) { granted ->
        if (granted.containsAll(permissions)) syncHealth() else status.text = "Health Connect permissions were not fully granted."
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val root = LinearLayout(this).apply { orientation = LinearLayout.VERTICAL; setPadding(36, 40, 36, 36) }
        fun add(v: android.view.View) { root.addView(v, LinearLayout.LayoutParams(-1, LinearLayout.LayoutParams.WRAP_CONTENT).apply { setMargins(0, 0, 0, 18) }) }
        val title = TextView(this).apply { text = "AegisFit Android Health Connect"; textSize = 24f }
        serverUrl = EditText(this).apply { hint = "AegisFit server URL, e.g. http://192.168.1.5:3000"; setSingleLine(true); setText(getPreferences(0).getString("server", "http://10.0.2.2:3000")) }
        pairCode = EditText(this).apply { hint = "6-digit pairing code"; setSingleLine(true); inputType = 2 }
        val connect = Button(this).apply { text = "Allow Health Connect & Sync"; setOnClickListener { connectAndSync() } }
        val openSettings = Button(this).apply { text = "Open Health Connect settings"; setOnClickListener { openHealthSettings() } }
        status = TextView(this).apply { text = "Enter the server URL and the pairing code generated by AegisFit → Devices."; textSize = 16f }
        add(title); add(serverUrl); add(pairCode); add(connect); add(openSettings); add(status)
        setContentView(root)
        val sdk = HealthConnectClient.getSdkStatus(this, "com.aegisfit.healthconnect")
        if (sdk == HealthConnectClient.SDK_UNAVAILABLE) status.text = "Health Connect is unavailable on this phone. Android 14+ includes it; Android 13 and lower need the Health Connect app."
        else if (sdk == HealthConnectClient.SDK_UNAVAILABLE_PROVIDER_UPDATE_REQUIRED) status.text = "Update/install Health Connect, then try again."
        else client = HealthConnectClient.getOrCreate(this)
    }

    private fun connectAndSync() {
        if (!::client.isInitialized) { Toast.makeText(this, "Health Connect is not available yet.", Toast.LENGTH_LONG).show(); return }
        getPreferences(0).edit().putString("server", serverUrl.text.toString().trim().removeSuffix("/")).apply()
        lifecycleScope.launch {
            try {
                val granted = client.permissionController.getGrantedPermissions()
                if (!granted.containsAll(permissions)) { permissionLauncher.launch(permissions); return@launch }
                syncHealth()
            } catch (e: Exception) { status.text = "Permission error: ${e.message}" }
        }
    }

    private fun syncHealth() {
        lifecycleScope.launch {
            try {
                val end = Instant.now(); val start = end.minus(1, ChronoUnit.DAYS)
                val range = TimeRangeFilter.between(start, end)
                val agg = client.aggregate(AggregateRequest(setOf(StepsRecord.COUNT_TOTAL, TotalCaloriesBurnedRecord.ENERGY_TOTAL), range))
                val steps = agg[StepsRecord.COUNT_TOTAL] ?: 0L
                val calories = (agg[TotalCaloriesBurnedRecord.ENERGY_TOTAL]?.inKilocalories ?: 0.0).roundToInt()
                val hr = client.readRecords(ReadRecordsRequest(HeartRateRecord::class, timeRangeFilter = range)).records
                    .flatMap { it.samples }.map { it.beatsPerMinute }.takeIf { it.isNotEmpty() }?.average()?.roundToInt()
                val body = JSONObject().apply { put("code", pairCode.text.toString().trim()); put("steps", steps); put("calories", calories); if (hr != null) put("avgHeartRate", hr); put("startTime", start.toString()); put("endTime", end.toString()); put("device", "Android Health Connect") }
                val result = postJson(serverUrl.text.toString().trim().removeSuffix("/") + "/api/healthconnect/sync", body)
                if (!result.optBoolean("ok")) throw IllegalStateException(result.optString("error", "Sync failed"))
                status.text = "Connected ✓ Synced last 24h — ${steps} steps, ${calories} kcal${if(hr!=null) ", ${hr} bpm avg" else ""}."
            } catch (e: Exception) { status.text = "Sync failed: ${e.message}" }
        }
    }

    private fun postJson(url: String, body: JSONObject): JSONObject {
        val c = URL(url).openConnection() as HttpURLConnection
        c.requestMethod = "POST"; c.connectTimeout = 10000; c.readTimeout = 15000; c.doOutput = true; c.setRequestProperty("Content-Type", "application/json")
        c.outputStream.use { it.write(body.toString().toByteArray()) }
        val text = (if (c.responseCode in 200..299) c.inputStream else c.errorStream).bufferedReader().use { it.readText() }
        if (c.responseCode !in 200..299) throw IllegalStateException(JSONObject(text).optString("error", "HTTP ${c.responseCode}"))
        return JSONObject(text)
    }

    private fun openHealthSettings() {
        try { startActivity(Intent("androidx.health.connect.action.HEALTH_CONNECT_SETTINGS")) }
        catch (_: Exception) { startActivity(Intent(Intent.ACTION_VIEW, Uri.parse("package:com.google.android.apps.healthdata"))) }
    }
}
